version: '3.8'

services:
  redis:
    image: redis
    expose:
      - 6379

  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=4000
