version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - 6379

  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REACT_APP_BACKEND_URL=localhost:3000
      - REDIS_URL=redis://redis:6379
      - PORT=3000
