version: '3.8'

services:
  redis:
    image: redis
    expose:
      - 6379

  client:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

  server:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_URL=
