version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - 6379

  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - redis
    depends_on:
      - redis
    environment:
      # - REACT_APP_BACKEND_URL is not set as it will gracefully
      #   default to the current hostname.
      - REDIS_URL=redis://redis:6379
      - PORT=${SERVER_PORT}
