version: 2.1

commands:
  set-preview-env-vars:
    steps:
      - run:
          name: Add preview environment variables
          command: |
            export GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            echo "export BUILD_PATH='/build/$GIT_HASH'" >> $BASH_ENV

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build:
          name: build:prod
          is-preview: false
          filters:
            branches:
              only: master
      - build:
          name: build:preview
          is-preview: true
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build:prod
          filters:
            branches:
              only: master
      - deploy:
          name: deploy:preview
          is-preview: true
          requires:
            - build:preview
          filters:
            branches:
              ignore: master

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-stretch-browsers
    working_directory: ~/repo
    parameters:
      is-preview:
        type: boolean
        default: false
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test
      - when:
          condition: << parameters.is-preview>>
          steps:
            - set-preview-env-vars
            - run:
                name: Create preview build
                command: PREVIEW_PATH=$BUILD_PATH yarn build
      - unless:
          condition: << parameters.is-preview>>
          steps:
            - run:
                name: Create production build
                command: yarn build
      - run:
          name: Export
          command: yarn export
      # make the `/out` directory available to the deploy job
      - persist_to_workspace:
          root: ~/repo
          paths:
            - out
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    parameters:
      is-preview:
        type: boolean
        default: false
    steps:
      # make the `/out` directory accessible
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli

      # deploy to production when on master
      - unless:
          condition: << parameters.is-preview >>
          steps:
            - run:
                name: Deploy to S3
                command: aws s3 sync out s3://${S3_BUCKET_DIST}/ --delete  --acl public-read --cache-control max-age=604800
            - run:
                name: Cloudfront invalidation
                command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

      # deploy to preview bucket on other
      - when:
          condition: << parameters.is-preview >>
          steps:
            - set-preview-env-vars
            - run:
                name: Deploy preview to S3
                command: aws s3 sync out s3://${S3_BUCKET_PREVIEW}${BUILD_PATH}/ --acl public-read --cache-control max-age=604800
            - run:
                name: Notify GitHub PR
                command: |
                  echo "{
                    \"state\": \"success\",
                    \"target_url\": \"https://$S3_BUCKET_PREVIEW$BUILD_PATH\",
                    \"description\": \"Here's a preview\",
                    \"context\": \"ci/circleci: preview\"
                  }" > body.json
                  curl -X POST \
                    -H "Authorization: token ${GH_TOKEN}" \
                    -H "Content-type: application/json" \
                    -d @body.json \
                    https://api.github.com/repos/alexbassy/site/statuses/$CIRCLE_SHA1
